### ISSUE TITLE
Some errors occur in importing C_ROIPooling

### ISSUE THREAD

**Issue by yyxx1997** [ELFEamp/PMR-baseline-VL-BERT#1]
~~~
Here are the error texts:
/suda/PMR/PMR-baseline-VL-BERT/pmr/../common/lib/roi_pooling/__init__.py)
Traceback (most recent call last):
  File "pmr/train_end2end.py", line 8, in <module>
    from pmr.function.train import train_net
  File "/data1/yx/suda/PMR/PMR-baseline-VL-BERT/pmr/../pmr/function/train.py", line 26, in <module>
    from pmr.modules import *
  File "/data1/yx/suda/PMR/PMR-baseline-VL-BERT/pmr/../pmr/modules/__init__.py", line 1, in <module>
    from .resnet_vlbert_for_vcr import ResNetVLBERT
  File "/data1/yx/suda/PMR/PMR-baseline-VL-BERT/pmr/../pmr/modules/resnet_vlbert_for_vcr.py", line 7, in <module>
    from common.fast_rcnn import FastRCNN
  File "/data1/yx/suda/PMR/PMR-baseline-VL-BERT/pmr/../common/fast_rcnn.py", line 10, in <module>
    from common.lib.roi_pooling.roi_pool import ROIPool
  File "/data1/yx/suda/PMR/PMR-baseline-VL-BERT/pmr/../common/lib/roi_pooling/__init__.py", line 1, in <module>
    from .roi_align import ROIAlign
  File "/data1/yx/suda/PMR/PMR-baseline-VL-BERT/pmr/../common/lib/roi_pooling/roi_align.py", line 8, in <module>
    from . import C_ROIPooling
ImportError: cannot import name 'C_ROIPooling' from partially initialized module 'common.lib.roi_pooling' (most likely due to a circular import) (/data1/yx/suda/PMR/PMR-baseline-VL-BERT/pmr/../common/lib/roi_pooling/__init__.py)
~~~
----------------------------------------------------------
Please tell me what I can do? 
Have you experienced similar situations during the experiment?

**Comment by corlder** [comment]
We didn't meet this error. Do you assert [all the requirements](https://github.com/jackroos/VL-BERT#environment) have been installed correctly? Would you mind providing more details about the environment?

**Comment by yyxx1997** [comment]
> We didn't meet this error. Do you assert [all the requirements](https://github.com/jackroos/VL-BERT#environment) have been installed correctly? Would you mind providing more details about the environment?

Thanks for your reply! I have solved this problem. The reason is that I had not firstly execute [/script/init.sh](https://github.com/ELFEamp/PMR-baseline-VL-BERT/blob/master/scripts/init.sh) before.
